### ISSUE TITLE
install issue, not executable

### ISSUE THREAD

**Issue by jeroenkl** [123electric/SmartMeter-DBus#1]
Followed the insallation instruction:
_From PackageManager, add a new package. Github username: 123electric Repository: SmartMeter-DBus Branch: latest_

Got the following error in Venus OS package manager:
_setup file for SmartMeter-DBus not executable_

Please advise how to proceed.
thanks in advance!

**Comment by jeroenkl** [comment]
root@raspberrypi2:/data/SmartMeter-DBus# ./setup
--- starting setup script v1.1
**unexpected script action NONE - did not install or uninstall
completed**
root@raspberrypi2:/data/SmartMeter-DBus#

**Comment by AlbertronicDev** [comment]
Hi Jeroen,
Sorry, I missed this issue. The file permissions on Github were not set correctly. I just fixed it. Please press again on download and then on Install. It should work now.
